[build]
  publish = "_site"

[[redirects]]
  from = "/"
  to = "/magicgreenpages.json"
  status = 302

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
  # in final stage restrict to proper site url only as is :
  # Access-Control-Allow-Origin: https://magicgreen.junglestar.org
